config/routes.rb
FbAstro::Application.routes.draw do
  resources :people, :only => [:edit, :update]

  resources :horoscopes, :only => [:show] do
    member do
			put 'publish'
		  put 'share'
    end
  end
  resources :astro, :only => [:index]
  put "astro/like"

  get "facebook/auth"

  get "facebook/close"

  get "facebook/callback"

  root :to => 'astro#index'

end

app/models/horoscope.rb
class Horoscope < ActiveRecord::Base
  WESTERN_SIGNS = ['aries', 'taurus', 'gemini', 'cancer', 'leo', 'virgo', 'libra', 'scorpio', 'sagittarius', 'capricorn', 'aquarius', 'pisces']
  attr_accessible :name, :solutions_feed
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_person
  #TODO Handle errors for applications
  # Koala::Facebook::APIError
  # Koala::Facebook::APIError (OAuthException: (#506) Duplicate status message)

  def current_person
    @current_person ||= Person.find_by_uid(session[:current_uid])
  end

  private

    def request_authorization
      # FB doesn't like port numbers in the return URL in canvas apps
      full_host = request.host
      full_host += ':' + request.port.to_s if request.host == 'localhost'
      return_url = "#{request.protocol}#{full_host}#{request.fullpath}"
      logger.info 'FB Auth Return URL: ' + return_url
      session['oauth'] = Koala::Facebook::OAuth.new(ENV['ASTRO_FACEBOOK_APP_ID'], ENV['ASTRO_FACEBOOK_APP_SECRET'], return_url)
      redirect_to session['oauth'].url_for_oauth_code(:permissions => 'user_birthday,friends_birthday,publish_actions,publish_stream,read_stream')
    end

    def verify_access_token
      unless session['access_token']
        if session['oauth'] && params[:code]
          # Use the code returned by Facebook to get an access token
          session['access_token'] = session['oauth'].get_access_token(params[:code])
        else
          # Coming in cold so ask for auth
          request_authorization && return
        end
      end

      @graph = Koala::Facebook::API.new(session['access_token'])

      # Need to get an actual object to test the access token
      @current_graph = @graph.get_object("me")
      session['current_uid'] = @current_graph['id']
   
      unless Person.find_by_uid(@current_graph['id'])
        sign = @current_graph['birthday'].nil? ? 'Aries' : return_sign(@current_graph['birthday']) 
        Person.create!(:uid => @current_graph['id'], :sign => sign )
      end
          
      
    rescue Koala::Facebook::APIError
      session['access_token'] = nil
      request_authorization
    end

    def return_sign(birthday)    
		  birthday += "/2012" if birthday.count("/") == 1
		  birthday = Date.strptime(birthday, "%m/%d/%Y")
		  month = birthday.strftime("%m").to_i
		  day = birthday.strftime("%d").to_i
		  AstrologyLib.sign_from_date(month,day).try(:capitalize)
    end

end

app/controllers/astro_controller.rb
class AstroController < ApplicationController
  before_filter :verify_access_token, :only => [:index, :like]

  def index
    @horoscopes = Horoscope.all
    begin
      @friends = KoalaService.get_friends(@graph)
    rescue Koala::Facebook::APIError
      logger.info "Koala API error"
    end
  end

  def like
    KoalaService.like!(@graph)
  end

end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController
  def auth
  end

  def close
  end

  def callback
  end
end

app/controllers/horoscopes_controller.rb
class HoroscopesController < ApplicationController
  before_filter :verify_access_token, :except => [:show]
  #before_filter :check_if_user_has_fb_account, :only => [:publish, :share]
  before_filter :get_horoscope

  def show
    @content = Metis.get_today(current_person.sign, @horoscope.solutions_feed)
    session[:horoscope_content] = @content
  end

  def publish
    begin
      KoalaService.post_on_my_wall(@graph, session[:horoscope_content])
    rescue Exception => e
      puts 'Exception when publishing content'
    end
    respond_to do |format|
      format.js { render :layout => false }
      format.html { render :layout => false }
    end
  end

  def share
    begin
      KoalaService.post_on_friends_wall(@graph, session[:horoscope_content], params[:uid])
    rescue Exception => e
    	puts 'Exception when sharing content'
    end
  end


  private

  def get_horoscope
    @horoscope = Horoscope.find params[:id]
  end

  def check_if_user_has_fb_account
    @can_post_to_fb = true if @graph
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :find_person

  def edit
    respond_to do |format|
    	format.html { render :layout => false }
      format.js { render :layout => false }
    end
  end

  def update
    if @person.update_attributes(params[:person])
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.js
      end
    end
  end

  private

  def find_person
    @person = current_person
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/astro_helper.rb
module AstroHelper
end

app/helpers/facebook_helper.rb
module FacebookHelper
end

app/helpers/horoscopes_helper.rb
module HoroscopesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/astro/_friends.html.erb
<h4 class='fb'>Friends</h4>
    <div class='padder fb'>
      <div class='label fb'>My friends</div>
      <div class='description fb'>
        <p style='margin-top: 0px'>
        Here is list of your friends you can share your content.
        </p>
        <p>
<% @friends.each do |friend| -%>
        <a class='portrait fb' href='https://www.facebook.com/<%=friend['id']%>' target='_top'>
          <img src="https://graph.facebook.com/<%=friend['id']%>/picture">
        	<%= friend['name'] %>  
        </a>
<%= link_to 'Share', share_horoscope_path(@horoscopes.first, :uid => friend['id']), :method => :put %>
<% end -%>
        </p>
      </div>
      <br clear='all'>
    </div>

app/views/astro/index.html.erb
  <h4 class='fb'>Pick horoscope type</h4>
  <div class='padder fb'>
    <div class='label fb'>Horoscopes</div>
    <div class='description fb'>
      <p style='margin-top: 0px'>Choose one of the horoscopes to see some fresh content.</p>
    </div>
    <div class='label fb'>Spread the word</div>
    <div class='description fb'>
      <p style='margin-top: 0px'>
			<%= link_to 'Publish this', publish_horoscope_path(@horoscopes.first), :method => :put %>
      Your sign:<%= current_person.sign %> <%= link_to 'Change sign', edit_person_path(current_person), :rel => "facebox", :remote => true %>
      </p>
      <p>
			<% @horoscopes.each do |horoscope| -%>
				<%= link_to horoscope.name, horoscope_path(horoscope), :remote => true %>
			<% end -%>
      </p>
      <div id="horoscope">
      	
      </div>
    </div>
    <br clear='all'>


<%= render :partial => "friends", :friends => @friends %>

app/views/astro/index.html.haml
%h1 Astro#index
%p
  Name:
  = @current_person['name']
%p
  Birthday:
  = @current_person['birthday']

%h2 Friends
%p TODO

app/views/facebook/auth.html.haml
%h1 Facebook#auth
%p Find me in app/views/facebook/auth.html.haml

app/views/facebook/callback.html.haml
%h1 Facebook#callback
%p Find me in app/views/facebook/callback.html.haml

app/views/facebook/close.html.haml
%h1 Facebook#close
%p Find me in app/views/facebook/close.html.haml

app/views/horoscopes/_show.html.erb
<%= @content %>

<div class="fb-like" data-href="https://apps.facebook.com/astrologydev/" data-send="false" data-width="450" data-show-faces="false"></div>

<script language="javascript" type="text/javascript">
        $(document).ajaxComplete(function(){
    try{
        FB.XFBML.parse(); 
    }catch(ex){}
});
</script>

app/views/horoscopes/publish.html.erb
You published the app 
<%= link_to 'Back', root_path %>

app/views/horoscopes/share.html.erb
You shared the app 
<%= link_to 'Back', root_path %>

app/views/horoscopes/show.html.haml
%h1 Horoscopes#show
%p Find me in app/views/horoscopes/show.html.haml

app/views/horoscopes/show.js.erb
$('#horoscope').html("")
$('#horoscope').html("<%= escape_javascript(render 'show', :content => @content) %>"); 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AstrologyFacebook</title>
    <%= stylesheet_link_tag "application", 'facebox' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script-->
  <%= javascript_include_tag 'facebox' %>
  <script type="text/javascript">
    jQuery(document).ready(function($) {
      $('a[rel*=facebox]').facebox({
        loadingImage : '/images/loading.gif',
        closeImage   : '/images/closelabel.png'
      })
    })
  </script>
  </head>

  <body>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=389241711100927";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

  <div class='page_title'>
    <img src='https://graph.facebook.com/237278599679568/picture'>
    <h3>Astrology Horoscope</h3>
  </div>
  <br clear='all'/>

  <%= yield %>

  </div>
</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Astrology.com
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/people/_form.html.erb
<%= form_for @person do |f| -%>

      <%= f.label :sign, :class => 'control-label' %>
      <%= f.select :sign, Horoscope::WESTERN_SIGNS.map{|s| [s.capitalize,s.capitalize]} %>

      <%= f.submit "Change sign" %>	
<% end -%>

app/views/people/edit.html.erb
<%= render :partial => 'form' %>

app/views/people/edit.js.erb
<%= render :partial => 'form' %>

app/views/people/update.html.haml
%h1 People#update
%p Find me in app/views/people/update.html.haml